/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/pages/StudentsPage copy 2.vue')['default']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AuthPage: typeof import('./src/components/pages/AuthPage.vue')['default']
    copy: typeof import('./src/components/pages/StudentsPage copy.vue')['default']
    FinanceAnalyticsPage: typeof import('./src/components/pages/FinanceAnalyticsPage.vue')['default']
    FormSchema: typeof import('./src/components/FormSchema.vue')['default']
    LessonPage: typeof import('./src/components/pages/LessonPage.vue')['default']
    LessonsAnalyticsPage: typeof import('./src/components/pages/LessonsAnalyticsPage.vue')['default']
    LessonsPage: typeof import('./src/components/pages/LessonsPage.vue')['default']
    MainAside: typeof import('./src/components/layout/MainAside.vue')['default']
    MainHeader: typeof import('./src/components/layout/MainHeader.vue')['default']
    MainPage: typeof import('./src/components/pages/MainPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentsPage: typeof import('./src/components/pages/StudentsPage.vue')['default']
    TeachersPage: typeof import('./src/components/pages/TeachersPage.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
